version: '3'

services:
  postgres:
    image: postgres:15
    restart: always
    ports:
      - 5432:5432
    volumes:
        - ./postgres-data:/var/lib/postgresql/data  
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  
networks:
  default:
    driver: bridge